"""tenants_and_domain_models

Revision ID: a5cb24869a7c
Revises: f265f3618387
Create Date: 2026-05-18 20:45:43.765560

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision: str = 'a5cb24869a7c'
down_revision: Union[str, Sequence[str], None] = 'f265f3618387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Phase A single-tenant: every existing user/row is implicitly owned by this
# tenant. Must match src/tenant/constants.py:DEFAULT_TENANT_ID.
_DEFAULT_TENANT_ID = uuid.UUID("00000000-0000-0000-0000-000000000001")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('owner_email', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('pending_verification', 'pending_setup', 'active', 'suspended', name='tenantstatus', native_enum=False, length=40), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('setup_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=False),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)

    # Seed the default tenant for single-tenant Phase A. The conftest does the
    # equivalent for the test backends; this keeps prod aligned.
    _tenants = table(
        "tenants",
        column("id", sa.Uuid()),
        column("business_name", sa.String()),
        column("slug", sa.String()),
        column("owner_email", sa.String()),
        column("status", sa.String()),
        column("accent_color", sa.String()),
    )
    op.bulk_insert(
        _tenants,
        [
            {
                "id": _DEFAULT_TENANT_ID,
                "business_name": "Default",
                "slug": "default",
                "owner_email": "admin@example.local",
                "status": "pending_setup",
                "accent_color": "#2E75B6",
            }
        ],
    )

    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_tenant_created', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('payment_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('account_no', sa.String(length=80), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=False),
    sa.Column('webhook_secret_enc', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_result', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_configs_tenant_id'), 'payment_configs', ['tenant_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_ugx', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('speed_down_kbps', sa.Integer(), nullable=True),
    sa.Column('speed_up_kbps', sa.Integer(), nullable=True),
    sa.Column('data_limit_mb', sa.Integer(), nullable=True),
    sa.Column('data_limit_down_mb', sa.Integer(), nullable=True),
    sa.Column('data_limit_up_mb', sa.Integer(), nullable=True),
    sa.Column('separate_limits', sa.Boolean(), nullable=False),
    sa.Column('simultaneous_devices', sa.Integer(), nullable=False),
    sa.Column('available_days', sa.JSON(), nullable=False),
    sa.Column('available_from', sa.Time(), nullable=True),
    sa.Column('available_until', sa.Time(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('display_color', sa.String(length=7), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_tenant_id'), 'plans', ['tenant_id'], unique=False)
    op.create_table('routers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('registration_token_hash', sa.String(length=128), nullable=False),
    sa.Column('wireguard_pubkey', sa.String(length=64), nullable=True),
    sa.Column('tunnel_ip', sa.String(length=45), nullable=True),
    sa.Column('api_password_enc', sa.Text(), nullable=True),
    sa.Column('router_model', sa.String(length=50), nullable=True),
    sa.Column('routeros_version', sa.String(length=20), nullable=True),
    sa.Column('hotspot_server_name', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('pending_script', 'online', 'offline', name='routerstatus', native_enum=False, length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routers_tenant_id'), 'routers', ['tenant_id'], unique=False)
    op.create_index('ix_routers_tenant_status', 'routers', ['tenant_id', 'status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('router_id', sa.Uuid(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('amount_ugx', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'provisioning', 'completed', 'failed', 'expired', name='transactionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('relworx_internal_ref', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.Enum('mtn_uganda', 'airtel_uganda', name='paymentprovider', native_enum=False, length=20), nullable=False),
    sa.Column('relworx_charge_ugx', sa.Integer(), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('mikrotik_username', sa.String(length=80), nullable=True),
    sa.Column('mikrotik_password', sa.String(length=80), nullable=True),
    sa.Column('webhook_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provisioning_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_relworx_internal_ref'), 'transactions', ['relworx_internal_ref'], unique=False)
    op.create_index('ix_transactions_tenant_created', 'transactions', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_tenant_id'), 'transactions', ['tenant_id'], unique=False)
    op.create_index('ix_transactions_tenant_status_created', 'transactions', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('router_id', sa.Uuid(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mikrotik_username', sa.String(length=80), nullable=False),
    sa.Column('bytes_used', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('ix_sessions_expires_active', 'sessions', ['expires_at', 'is_active'], unique=False)
    op.create_index(op.f('ix_sessions_tenant_id'), 'sessions', ['tenant_id'], unique=False)
    op.create_index('ix_sessions_tenant_is_active', 'sessions', ['tenant_id', 'is_active'], unique=False)
    # Add users.tenant_id in three steps so any existing rows get backfilled
    # before the NOT NULL + FK constraints lock in.
    op.add_column('users', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.execute(
        sa.text("UPDATE users SET tenant_id = :tid").bindparams(tid=_DEFAULT_TENANT_ID)
    )
    op.alter_column('users', 'tenant_id', nullable=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'tenant_id')
    op.drop_index('ix_sessions_tenant_is_active', table_name='sessions')
    op.drop_index(op.f('ix_sessions_tenant_id'), table_name='sessions')
    op.drop_index('ix_sessions_expires_active', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_transactions_tenant_status_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_tenant_id'), table_name='transactions')
    op.drop_index('ix_transactions_tenant_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_relworx_internal_ref'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_routers_tenant_status', table_name='routers')
    op.drop_index(op.f('ix_routers_tenant_id'), table_name='routers')
    op.drop_table('routers')
    op.drop_index(op.f('ix_plans_tenant_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_payment_configs_tenant_id'), table_name='payment_configs')
    op.drop_table('payment_configs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
